// AWPL Wellness Products Database
// Real product details, prices (DP/MRP), Sizes, Sales Points (SP) and supply days (for CRM reminders)

const AWPL_PRODUCTS = [
  {
    id: "exe-panch-tulsi-oil",
    name: "EXE PANCH TULSI OIL",
    category: "Wellness",
    mrp: 404.00,
    dp: 349.00,
    sp: 2.00,
    size: "25.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T331_092352.jpg",
    benefits: "Supports immunity, helps in respiratory health, anti-bacterial & anti-oxidant properties."
  },
  {
    id: "adidoc-pravahi-kwath",
    name: "ADIDOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 444.00,
    dp: 383.00,
    sp: 2.00,
    size: "25.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T551_212707.jpg",
    benefits: "Herbal formulation to improve vitality and physical resistance against seasonal changes."
  },
  {
    id: "exe-triphala-pravahi-kwath",
    name: "EXE TRIPHALA PRAVAHI KWATH",
    category: "Wellness",
    mrp: 448.00,
    dp: 387.00,
    sp: 2.00,
    size: "500.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T531_152572.jpg",
    benefits: "Enriched with Amla, Haritaki, and Bibhitaki. Supports digestion, colon cleanse and detoxification."
  },
  {
    id: "prodoc-powder",
    name: "PRODOC POWDER",
    category: "Wellness",
    mrp: 713.00,
    dp: 568.00,
    sp: 3.00,
    size: "200.00 GM",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T301_750199.jpg",
    benefits: "Protein supplement enriched with essential vitamins and minerals to support daily nutrition."
  },
  {
    id: "kidgdoc-ras",
    name: "KIDGDOC RAS",
    category: "Wellness",
    mrp: 794.00,
    dp: 685.00,
    sp: 4.00,
    size: "250.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T251_483331.jpg",
    benefits: "Specially formulated for children's growth, brain development, and physical strength."
  },
  {
    id: "exe-aloevera-syrup",
    name: "EXE ALOEVERA SYRUP",
    category: "Wellness",
    mrp: 949.00,
    dp: 819.00,
    sp: 5.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T491_175017.jpg",
    benefits: "Natural aloe vera extract. Aids digestion, improves skin health, and acts as a cooling detox agent."
  },
  {
    id: "alrgydoc-pravahi-kwath",
    name: "ALRGYDOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 1255.00,
    dp: 1083.00,
    sp: 7.00,
    size: "500.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T581_456230.jpg",
    benefits: "Herbal support to build resistance against dust, pollen, and seasonal skin/respiratory allergies."
  },
  {
    id: "eyedoc-drop",
    name: "EYEDOC DROP",
    category: "Wellness",
    mrp: 1305.00,
    dp: 1128.00,
    sp: 7.00,
    size: "45.00 ML",
    supplyDays: 15,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T1091_948682.jpg",
    benefits: "Ayurvedic sterile eye drops. Soothes tired eyes, clears vision, and reduces irritation."
  },
  {
    id: "braindoc-pravahi-kwath",
    name: "BRAINDOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 1330.00,
    dp: 1148.00,
    sp: 7.00,
    size: "500.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T521_774383.jpg",
    benefits: "Nerve tonic to boost memory, improve focus, lower stress levels, and nourish brain tissues."
  },
  {
    id: "gynedoc-ras",
    name: "GYNEDOC RAS",
    category: "Wellness",
    mrp: 1442.00,
    dp: 1244.00,
    sp: 8.00,
    size: "500.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T461_787478.jpg",
    benefits: "Comprehensive health tonic for women. Regularizes cycles, boosts energy, and maintains hormonal balance."
  },
  {
    id: "diabodoc-ras",
    name: "DIABODOC RAS",
    category: "Wellness",
    mrp: 1460.00,
    dp: 1259.00,
    sp: 8.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T451_812400.jpg",
    benefits: "Helps manage blood sugar levels naturally with Jamun, Karela, and Gurmar."
  },
  {
    id: "livodoc-ras",
    name: "LIVODOC RAS",
    category: "Wellness",
    mrp: 1494.00,
    dp: 1289.00,
    sp: 8.00,
    size: "500.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T471_402158.jpg",
    benefits: "Liver protection syrup. Enhances appetite, treats fatty liver, and aids metabolic functions."
  },
  {
    id: "immunodoc-ras",
    name: "IMMUNODOC RAS",
    category: "Wellness",
    mrp: 2073.00,
    dp: 1789.00,
    sp: 12.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T441_806924.jpg",
    benefits: "Powerful immunity booster blend of Giloy, Tulsi, and Ginger. Fights infections and builds stamina."
  },
  {
    id: "thunderblast-ras",
    name: "THUNDERBLAST RAS",
    category: "Wellness",
    mrp: 2248.00,
    dp: 1939.00,
    sp: 13.00,
    size: "500.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T411_741213.jpg",
    benefits: "Premium energizer tonic. Enhances muscle strength, nerve vitality, and provides general energy."
  },
  {
    id: "thydoc-pravahi-kwath",
    name: "THYDOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 2435.00,
    dp: 2101.00,
    sp: 13.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T381_285864.jpg",
    benefits: "Supports thyroid gland wellness, aids metabolism regulation, and maintains hormonal harmony."
  },
  {
    id: "cardiodoc-ras",
    name: "CARDIODOC RAS",
    category: "Wellness",
    mrp: 2253.00,
    dp: 1945.00,
    sp: 13.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T421_913989.jpg",
    benefits: "Heart health supplement. Formulated with Arjuna bark to strengthen cardiac muscles and regulate circulation."
  },
  {
    id: "pilodoc-ras",
    name: "PILODOC RAS",
    category: "Wellness",
    mrp: 2403.00,
    dp: 2074.00,
    sp: 13.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T371_837757.jpg",
    benefits: "Relieves constipation, shrinks piles/hemorrhoids mass, and reduces rectal burning and pain."
  },
  {
    id: "chlorodoc-pravahi-kwath",
    name: "CHLORODOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 2421.00,
    dp: 2089.00,
    sp: 13.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T391_556221.jpg",
    benefits: "Chlorophyll-enriched antioxidant drink. Helps purify blood, detoxify body, and increase hemoglobin."
  },
  {
    id: "orthodoc-pravahi-kwath",
    name: "ORTHODOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 2250.00,
    dp: 1941.00,
    sp: 13.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T401_053973.jpg",
    benefits: "Complete joint care formulation. Lubricates joints, reduces pain and swelling, and prevents bone decay."
  },
  {
    id: "stondoc-ras",
    name: "STONDOC RAS",
    category: "Wellness",
    mrp: 2507.00,
    dp: 2163.00,
    sp: 14.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T361_371339.jpg",
    benefits: "Kidney stone care. Helps disintegrate and flush out urinary stones and prevents UTI."
  },
  {
    id: "obeodoc-ras",
    name: "OBEODOC RAS",
    category: "Wellness",
    mrp: 2541.00,
    dp: 2192.00,
    sp: 15.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T351_122116.jpg",
    benefits: "Natural weight management formula. Boosts metabolism, suppresses appetite, and burns fat."
  },
  {
    id: "exe-punarnava-kwath",
    name: "EXE PUNARNAVA KWATH",
    category: "Wellness",
    mrp: 1144.00,
    dp: 960.00,
    sp: 5.00,
    size: "500.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T2021_379136.jpg",
    benefits: "Rejuvenates kidney cells, reduces edema, acts as a natural diuretic and detoxifier."
  },
  {
    id: "asclepius-chyawanprash-avaleha",
    name: "ASCLEPIUS CHYAWANPRASH AVALEHA",
    category: "Wellness",
    mrp: 498.00,
    dp: 365.00,
    sp: 1.00,
    size: "500.00 GM",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T2041_215136.jpg",
    benefits: "Rich source of Vitamin C. Enhances immune response, digestive tract health, and skin texture."
  },
  {
    id: "exe-herbal-tea",
    name: "EXE HERBAL TEA",
    category: "Wellness",
    mrp: 526.00,
    dp: 404.00,
    sp: 2.00,
    size: "100.00 GM",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T2141_553134.jpg",
    benefits: "Rich in antioxidants. Aids digestion, relieves mental fatigue, and boosts metabolism."
  },
  {
    id: "fevodoc-pravahi-kwath",
    name: "FEVODOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 2477.00,
    dp: 1973.00,
    sp: 12.00,
    size: "1000.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T2161_898860.jpg",
    benefits: "Indicated in chronic fevers, viral infections, dengue, and helps increase platelet counts."
  },
  {
    id: "coughdoc-pravahi-kwath",
    name: "COUGHDOC PRAVAHI KWATH",
    category: "Wellness",
    mrp: 543.00,
    dp: 433.00,
    sp: 2.00,
    size: "200.00 ML",
    supplyDays: 15,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T2171_476437.jpg",
    benefits: "Non-drowsy cough syrup. Provides fast relief from dry/wet cough, sore throat, and congestion."
  },
  {
    id: "exe-jc-oint",
    name: "EXE JC OINT",
    category: "Wellness",
    mrp: 475.00,
    dp: 366.00,
    sp: 2.00,
    size: "50.00 GM",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T2181_901752.jpeg",
    benefits: "Joint Curator Ointment. Offers instant relief from localized muscular pains, joint aches, and stiffness."
  },
  {
    id: "exe-veindoc-oil",
    name: "EXE VEINDOC OIL",
    category: "Wellness",
    mrp: 495.00,
    dp: 380.00,
    sp: 2.00,
    size: "50.00 ML",
    supplyDays: 30,
    image: "https://awpl-kycdocs.s3.ap-south-1.amazonaws.com/upload1/product/_T2191_884318.jpg",
    benefits: "Varicose veins wellness oil. Promotes healthy blood flow and relieves leg fatigue."
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { AWPL_PRODUCTS };
}
